// Lightbase collection schema definitions for GoShop Beta.
// BismiLLAH Ar-Rahman Ar-Roheem. Maps the legacy SQLite tables to Lightbase collections.
// Note: Lightbase auto-manages reserved fields (id, _created_at, _updated_at, _revision, _deleted, _checksum).
// We expose camelCase field names so the provider returns camelCase documents directly (no snake_case conversion).

type FieldType =
  | 'string' | 'text' | 'number' | 'integer' | 'boolean' | 'datetime'
  | 'json' | 'email' | 'url' | 'phone' | 'uuid';

interface FieldDef {
  name: string;
  type: FieldType;
  required?: boolean;
  unique?: boolean;
  indexed?: boolean;
  default?: any;
}

function f(name: string, type: FieldType, opts: Partial<FieldDef> = {}): FieldDef {
  return { name, type, ...opts };
}

export const SCHEMA: Record<string, FieldDef[]> = {
  users: [
    f('email', 'email', { required: true, unique: true, indexed: true }),
    f('passwordHash', 'string'),
    f('name', 'string'),
    f('firstName', 'string'),
    f('lastName', 'string'),
    f('avatar', 'url'),
    f('role', 'string', { default: 'customer' }),
    f('roles', 'json', { default: ['customer'] }),
    f('onboardingCompleted', 'boolean', { default: false }),
    f('businessName', 'string'),
    f('phone', 'phone'),
    f('address', 'text'),
    f('verified', 'boolean', { default: false }),
    f('permissions', 'json'),
    f('walletBalance', 'number', { default: 0 }),
    f('language', 'string', { default: 'en' }),
    f('currency', 'string', { default: 'USD' }),
    f('referralCode', 'string', { unique: true, indexed: true }),
    f('referredBy', 'string', { indexed: true }),
    f('referralEarnings', 'number', { default: 0 }),
    f('referralCount', 'integer', { default: 0 }),
  ],
  products: [
    f('name', 'string', { required: true }),
    f('description', 'text'),
    f('images', 'json', { default: [] }),
    f('price', 'number', { required: true, default: 0 }),
    f('originalPrice', 'number'),
    f('discount', 'number', { default: 0 }),
    f('rating', 'number', { default: 0 }),
    f('reviewCount', 'integer', { default: 0 }),
    f('category', 'string', { indexed: true }),
    f('storeId', 'string', { indexed: true }),
    f('sellerId', 'string', { indexed: true }),
    f('sellerName', 'string'),
    f('inventory', 'integer', { default: 0 }),
    f('tags', 'json', { default: [] }),
    f('isFeatured', 'boolean', { default: false, indexed: true }),
    f('isActive', 'boolean', { default: true }),
    f('sku', 'string'),
    f('weight', 'number'),
    f('dimensions', 'string'),
    f('shippingClass', 'string'),
    f('seoTitle', 'string'),
    f('seoDescription', 'text'),
    f('metaKeywords', 'string'),
    f('soldCount', 'integer', { default: 0 }),
    f('cloudinaryId', 'string'),
    f('type', 'string', { default: 'simple' }),
    f('variations', 'json', { default: [] }),
    f('variants', 'json', { default: [] }),
    f('bundles', 'json', { default: [] }),
    f('shippingEnabled', 'boolean', { default: true }),
    f('shippingCost', 'number', { default: 0 }),
    f('affiliateEnabled', 'boolean', { default: false }),
    f('affiliateCommission', 'number', { default: 0 }),
    f('currency', 'string', { default: 'USD' }),
    f('brand', 'string'),
    f('specifications', 'json', { default: {} }),
  ],
  categories: [
    f('name', 'string', { required: true }),
    f('slug', 'string', { required: true, unique: true, indexed: true }),
    f('description', 'text'),
    f('image', 'url'),
    f('icon', 'string'),
    f('parentId', 'string'),
    f('isActive', 'boolean', { default: true }),
    f('sortOrder', 'integer', { default: 0 }),
  ],
  orders: [
    f('userId', 'string', { required: true, indexed: true }),
    f('items', 'json', { required: true, default: [] }),
    f('total', 'number', { required: true, default: 0 }),
    f('subtotal', 'number'),
    f('platformCommission', 'number'),
    f('affiliateCommission', 'number'),
    f('shippingTotal', 'number'),
    f('paidAmount', 'number'),
    f('remainingAmount', 'number'),
    f('status', 'string', { default: 'pending', indexed: true }),
    f('paymentStatus', 'string', { default: 'pending' }),
    f('paymentMethod', 'string'),
    f('shippingAddress', 'json'),
    f('billingAddress', 'json'),
    f('sellerId', 'string', { indexed: true }),
    f('transactionRef', 'string'),
    f('deliveryMethod', 'string', { default: 'shipping' }),
    f('trackingNumber', 'string'),
    f('deliveredAt', 'datetime'),
    f('affiliateId', 'string'),
  ],
  cart_items: [
    f('userId', 'string', { required: true, indexed: true }),
    f('productId', 'string', { required: true }),
    f('quantity', 'integer', { default: 1 }),
  ],
  wishlist: [
    f('userId', 'string', { required: true, indexed: true }),
    f('productId', 'string', { required: true }),
  ],
  stores: [
    f('name', 'string', { required: true }),
    f('description', 'text'),
    f('logo', 'url'),
    f('banner', 'url'),
    f('address', 'text'),
    f('ownerId', 'string'),
    f('sellerId', 'string'),
    f('slug', 'string', { required: true, unique: true, indexed: true }),
    f('rating', 'number', { default: 0 }),
    f('reviewCount', 'integer', { default: 0 }),
    f('productCount', 'integer', { default: 0 }),
    f('isVerified', 'boolean', { default: false }),
    f('isApproved', 'boolean', { default: false }),
    f('isActive', 'boolean', { default: false }),
    f('location', 'string'),
    f('established', 'string'),
    f('totalSales', 'number', { default: 0 }),
    f('businessType', 'string'),
    f('website', 'url'),
    f('phone', 'phone'),
    f('email', 'email'),
    f('socialMedia', 'json', { default: {} }),
    f('policies', 'json', { default: {} }),
    f('categories', 'json', { default: [] }),
    f('tags', 'json', { default: [] }),
    f('bannerImages', 'json', { default: [] }),
  ],
  notifications: [
    f('userId', 'string', { required: true, indexed: true }),
    f('title', 'string', { required: true }),
    f('message', 'string', { required: true }),
    f('type', 'string', { default: 'info' }),
    f('read', 'boolean', { default: false }),
    f('link', 'string'),
  ],
  posts: [
    f('userId', 'string', { required: true }),
    f('userName', 'string'),
    f('userAvatar', 'url'),
    f('role', 'string', { default: 'seller' }),
    f('content', 'text'),
    f('images', 'json', { default: [] }),
    f('productIds', 'json', { default: [] }),
    f('storeId', 'string'),
    f('likes', 'integer', { default: 0 }),
    f('comments', 'integer', { default: 0 }),
    f('tags', 'json', { default: [] }),
    f('status', 'string', { default: 'pending', indexed: true }),
  ],
  comments: [
    f('postId', 'string', { required: true }),
    f('userId', 'string', { required: true }),
    f('userName', 'string'),
    f('userAvatar', 'url'),
    f('content', 'text'),
  ],
  wallets: [
    f('userId', 'string', { required: true, unique: true, indexed: true }),
    f('balance', 'number', { default: 0 }),
  ],
  transactions: [
    f('walletId', 'string', { required: true, indexed: true }),
    f('amount', 'number', { required: true }),
    f('type', 'string', { required: true }),
    f('description', 'text'),
    f('orderId', 'string'),
    f('productId', 'string'),
    f('status', 'string', { default: 'pending' }),
  ],
  blogs: [
    f('title', 'string', { required: true }),
    f('content', 'text'),
    f('excerpt', 'text'),
    f('slug', 'string', { required: true, unique: true, indexed: true }),
    f('author', 'string'),
    f('authorId', 'string'),
    f('storeId', 'string'),
    f('storeName', 'string'),
    f('category', 'string'),
    f('tags', 'json', { default: [] }),
    f('featuredImage', 'url'),
    f('isPublished', 'boolean', { default: false }),
  ],
  help_articles: [
    f('title', 'string', { required: true }),
    f('content', 'text'),
    f('category', 'string'),
    f('slug', 'string', { required: true, unique: true, indexed: true }),
    f('isPublished', 'boolean', { default: false }),
  ],
  reviews: [
    f('productId', 'string', { required: true, indexed: true }),
    f('userId', 'string', { required: true }),
    f('userName', 'string'),
    f('rating', 'integer', { required: true, default: 5 }),
    f('title', 'string'),
    f('content', 'text'),
    f('images', 'json', { default: [] }),
    f('isVerified', 'boolean', { default: false }),
  ],
  affiliate_links: [
    f('affiliateId', 'string', { required: true }),
    f('productId', 'string', { required: true }),
    f('collectionId', 'string'),
    f('code', 'string', { required: true, unique: true, indexed: true }),
    f('clicks', 'integer', { default: 0 }),
    f('conversions', 'integer', { default: 0 }),
    f('earnings', 'number', { default: 0 }),
    f('isActive', 'boolean', { default: true }),
  ],
  affiliate_collections: [
    f('affiliateId', 'string', { required: true }),
    f('name', 'string', { required: true }),
    f('description', 'text'),
    f('productIds', 'json', { default: [] }),
    f('linkCode', 'string', { required: true, unique: true, indexed: true }),
    f('isActive', 'boolean', { default: true }),
  ],
  refund_requests: [
    f('orderId', 'string', { required: true }),
    f('productId', 'string', { required: true }),
    f('customerId', 'string', { required: true }),
    f('sellerId', 'string', { required: true }),
    f('amount', 'number', { required: true }),
    f('reason', 'text'),
    f('status', 'string', { default: 'pending' }),
    f('adminNotes', 'text'),
    f('evidence', 'json', { default: [] }),
    f('resolvedAt', 'datetime'),
    f('resolvedBy', 'string'),
  ],
  disputes: [
    f('refundRequestId', 'string'),
    f('customerId', 'string', { required: true }),
    f('sellerId', 'string', { required: true }),
    f('adminId', 'string'),
    f('status', 'string', { default: 'open' }),
    f('messages', 'json', { default: [] }),
    f('resolution', 'text'),
  ],
  withdrawal_requests: [
    f('userId', 'string', { required: true }),
    f('userType', 'string', { default: 'customer' }),
    f('amount', 'number', { required: true }),
    f('bankDetails', 'json'),
    f('status', 'string', { default: 'pending' }),
    f('adminNotes', 'text'),
    f('processedAt', 'datetime'),
    f('processedBy', 'string'),
  ],
  platform_commissions: [
    f('percentage', 'number', { required: true, default: 5 }),
    f('category', 'string'),
    f('isGlobal', 'boolean', { default: false }),
  ],
  seller_agreements: [
    f('version', 'string'),
    f('content', 'text'),
    f('variables', 'json', { default: {} }),
    f('isActive', 'boolean', { default: false }),
  ],
  livestreams: [
    f('sellerId', 'string', { required: true }),
    f('title', 'string', { required: true }),
    f('description', 'text'),
    f('productIds', 'json', { default: [] }),
    f('status', 'string', { default: 'scheduled' }),
    f('startTime', 'datetime'),
    f('endTime', 'datetime'),
    f('agoraToken', 'string'),
  ],
  languages: [
    f('code', 'string', { required: true, unique: true, indexed: true }),
    f('name', 'string', { required: true }),
    f('nativeName', 'string'),
    f('flag', 'string'),
    f('rtl', 'boolean', { default: false }),
  ],
  currencies: [
    f('code', 'string', { required: true, unique: true, indexed: true }),
    f('name', 'string', { required: true }),
    f('symbol', 'string', { required: true }),
    f('exchangeRate', 'number', { required: true, default: 1 }),
  ],
  sessions: [
    f('userId', 'string', { required: true }),
    f('token', 'string', { required: true, unique: true, indexed: true }),
    f('expiresAt', 'datetime', { required: true }),
  ],
  referral_codes: [
    f('userId', 'string', { required: true, indexed: true }),
    f('code', 'string', { required: true, unique: true, indexed: true }),
    f('userType', 'string', { default: 'customer' }),
    f('clicks', 'integer', { default: 0 }),
    f('signups', 'integer', { default: 0 }),
    f('earnings', 'number', { default: 0 }),
    f('isActive', 'boolean', { default: true }),
  ],
};

export const COLLECTION_NAMES = Object.keys(SCHEMA);
